<a href="https://colab.research.google.com/github/ZaqueMendes/Linguagem_Python/blob/main/RSI_e_RSL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install ta
!pip install yfinance --upgrade --no-cache-dir
!pip install  mplfinance

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting ta
  Downloading ta-0.10.2.tar.gz (25 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from ta) (1.21.6)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from ta) (1.3.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->ta) (2022.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->ta) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->ta) (1.15.0)
Building wheels for collected packages: ta
  Building wheel for ta (setup.py) ... done
  Created wheel for ta: filename=ta-0.10.2-py3-none-any.whl size=29104 sha256=7135d35a6b1b066b5dca39c1a4ac111888efaf2ba6ce3d932d9456f897e120aa
  Stored in directory: /root/.cache/pip/wheels/31/31/f1/f2ff471bbc5b84a4b973698ceecdd453ae043971791adc3431
Successfully built ta
Installing collected packages: ta
Successfully installed ta-0.10.2
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting yfinance
  Downloading yfinance-0.1.84-py2.py3-none-any.whl (29 kB)
Requirement already satisfied: appdirs>=1.4.4 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.4.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.7/dist-packages (from yfinance) (0.0.11)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.21.6)
Collecting requests>=2.26
  Downloading requests-2.28.1-py3-none-any.whl (62 kB)
     |████████████████████████████████| 62 kB 15.7 MB/s
Requirement already satisfied: lxml>=4.5.1 in /usr/local/lib/python3.7/dist-packages (from yfinance) (4.9.1)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.3.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->yfinance) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->yfinance) (2022.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.24.0->yfinance) (1.15.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (1.24.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2022.9.24)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2.1.1)
Installing collected packages: requests, yfinance
  Attempting uninstall: requests
    Found existing installation: requests 2.23.0
    Uninstalling requests-2.23.0:
      Successfully uninstalled requests-2.23.0
Successfully installed requests-2.28.1 yfinance-0.1.84
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting mplfinance
  Downloading mplfinance-0.12.9b1-py3-none-any.whl (70 kB)
     |████████████████████████████████| 70 kB 3.9 MB/s
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from mplfinance) (1.3.5)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/dist-packages (from mplfinance) (3.2.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib->mplfinance) (0.11.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->mplfinance) (3.0.9)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->mplfinance) (1.4.4)
Requirement already satisfied: numpy>=1.11 in /usr/local/lib/python3.7/dist-packages (from matplotlib->mplfinance) (1.21.6)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->mplfinance) (2.8.2)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from kiwisolver>=1.0.1->matplotlib->mplfinance) (4.1.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.1->matplotlib->mplfinance) (1.15.0)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->mplfinance) (2022.5)
Installing collected packages: mplfinance
Successfully installed mplfinance-0.12.9b1

In [ ]:
# Carregando as bibliotecas necessarias
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import mplfinance as fplt
from pandas_datareader import data as pdr
from datetime import date
import ta
import yfinance as yf
yf.pdr_override()

import warnings
warnings.filterwarnings("ignore")

In [ ]:
# Parametros da funçao

indice = "^BVSP"
ativo1 = "PETR4.SA"
ativo2 = "FESA4.SA"
ativo3 = "JBSS3.SA"
ativo4 = "VALE3.SA"
ativo5 = "GGBR4.SA"

indice_close = indice
ativo1_close = ativo1
ativo2_close = ativo2
ativo3_close = ativo3
ativo4_close = ativo4
ativo5_close = ativo5



tickers = [indice, ativo1, ativo2, ativo3, ativo4, ativo5]



inicio = "2021-01-01"
fim = "2022-10-28"

In [ ]:
ibov = pdr.get_data_yahoo(tickers, start = inicio, end = fim)

[*********************100%***********************]  6 of 6 completed

In [ ]:
ibov

            Adj Close                                                        \
             FESA4.SA   GGBR4.SA   JBSS3.SA   PETR4.SA   VALE3.SA     ^BVSP
Date
2021-01-04  18.335793  21.918629  20.233704  15.694896  71.178856  118558.0
2021-01-05  18.269802  22.448917  20.527573  16.308359  72.377365  119223.0
2021-01-06  20.070389  23.526329  20.346066  16.340933  74.751030  119851.0
2021-01-07  21.578730  24.864679  20.596720  16.829533  79.630661  121956.0
2021-01-08  21.295918  24.494318  21.089378  16.894680  79.381622  125077.0
...               ...        ...        ...        ...        ...       ...
2022-10-21  53.779999  26.980000  25.750000  37.720001  74.129997  119929.0
2022-10-24  53.139999  26.860001  26.010000  34.250000  71.930000  116013.0
2022-10-25  51.779999  26.709999  25.900000  33.529999  71.930000  114626.0
2022-10-26  51.279999  26.639999  24.790001  32.709999  73.529999  112764.0
2022-10-27  51.349998  26.580000  24.930000  32.959999  70.910004  114641.0

                Close                                   ...       Open  \
             FESA4.SA   GGBR4.SA   JBSS3.SA   PETR4.SA  ...   JBSS3.SA
Date                                                    ...
2021-01-04  19.450001  26.040001  23.410000  28.910000  ...  23.900000
2021-01-05  19.379999  26.670000  23.750000  30.040001  ...  23.290001
2021-01-06  21.290001  27.950001  23.540001  30.100000  ...  23.750000
2021-01-07  22.889999  29.540001  23.830000  31.000000  ...  23.610001
2021-01-08  22.590000  29.100000  24.400000  31.120001  ...  23.910000
...               ...        ...        ...        ...  ...        ...
2022-10-21  53.779999  26.980000  25.750000  37.720001  ...  25.400000
2022-10-24  53.139999  26.860001  26.010000  34.250000  ...  25.469999
2022-10-25  51.779999  26.709999  25.900000  33.529999  ...  26.190001
2022-10-26  51.279999  26.639999  24.790001  32.709999  ...  25.690001
2022-10-27  51.349998  26.580000  24.930000  32.959999  ...  24.879999

                                              Volume                      \
             PETR4.SA    VALE3.SA     ^BVSP FESA4.SA  GGBR4.SA  JBSS3.SA
Date
2021-01-04  28.650000   89.349998  119024.0   180300  22156100  10914500
2021-01-05  28.900000   91.459999  118835.0   179100  17564800  17855900
2021-01-06  30.160000   94.980003  119377.0   893500  26790200  14518700
2021-01-07  30.340000   96.610001  119103.0   950000  20996500  16820400
2021-01-08  31.459999  103.010002  122387.0   382100  18035200  19156200
...               ...         ...       ...      ...       ...       ...
2022-10-21  36.450001   71.800003  117170.0   170400  11281700   7496400
2022-10-24  36.500000   73.269997  119922.0   131600  11343500   7674000
2022-10-25  34.040001   71.610001  116016.0   157000   7895100   8034900
2022-10-26  32.599998   71.279999  114626.0   158400  12954700  10249900
2022-10-27  32.810001   72.000000  112766.0   198600   9938600   5251300


             PETR4.SA  VALE3.SA     ^BVSP
Date
2021-01-04   74719700  37865500   8741400
2021-01-05   95181100  34300300   9257100
2021-01-06   96562500  53722500  11638200
2021-01-07   56171300  74541400  11774800
2021-01-08   67136300  58562700  11085800
...               ...       ...       ...
2022-10-21  139601400  36846800         0
2022-10-24  142110900  32035800  13278800
2022-10-25  113161200  28158100  14727200
2022-10-26  121334800  40845700  16088200
2022-10-27  111008800  52613000  15530800

[454 rows x 36 columns]

In [ ]:
ibov["Adj Close"][  tickers ]

               ^BVSP   PETR4.SA   FESA4.SA   JBSS3.SA   VALE3.SA   GGBR4.SA
Date
2021-01-04  118558.0  15.694896  18.335793  20.233704  71.178856  21.918629
2021-01-05  119223.0  16.308359  18.269802  20.527573  72.377365  22.448917
2021-01-06  119851.0  16.340933  20.070389  20.346066  74.751030  23.526329
2021-01-07  121956.0  16.829533  21.578730  20.596720  79.630661  24.864679
2021-01-08  125077.0  16.894680  21.295918  21.089378  79.381622  24.494318
...              ...        ...        ...        ...        ...        ...
2022-10-21  119929.0  37.720001  53.779999  25.750000  74.129997  26.980000
2022-10-24  116013.0  34.250000  53.139999  26.010000  71.930000  26.860001
2022-10-25  114626.0  33.529999  51.779999  25.900000  71.930000  26.709999
2022-10-26  112764.0  32.709999  51.279999  24.790001  73.529999  26.639999
2022-10-27  114641.0  32.959999  51.349998  24.930000  70.910004  26.580000

[454 rows x 6 columns]

df_mapa = ibov["Adj Close"][tickers]

In [ ]:
df_mapa = ibov["Adj Close"][tickers]

In [ ]:
tickers

['^BVSP', 'PETR4.SA', 'FESA4.SA', 'JBSS3.SA', 'VALE3.SA', 'GGBR4.SA']

In [ ]:
df_mapa.head()

               ^BVSP   PETR4.SA   FESA4.SA   JBSS3.SA   VALE3.SA   GGBR4.SA
Date
2021-01-04  118558.0  15.694895  18.335793  20.233704  71.178856  21.918627
2021-01-05  119223.0  16.308361  18.269806  20.527573  72.377365  22.448915
2021-01-06  119851.0  16.340931  20.070387  20.346066  74.751030  23.526331
2021-01-07  121956.0  16.829533  21.578730  20.596718  79.630661  24.864679
2021-01-08  125077.0  16.894678  21.295916  21.089380  79.381630  24.494318

In [ ]:
#df_mapa.rename(columns = {"indice" : "indice_close" , "ativo1" : "ativo_close",
 #    "ativo2" : "ativo2_close", "ativo3" : "ativo3_close", "ativo4" : "ativo4_close", "ativo5" : "ativo5_close"}, inplace = True)                    
               
#df_mapa.head()

               ^BVSP   PETR4.SA   FESA4.SA   JBSS3.SA   VALE3.SA   GGBR4.SA
Date
2021-01-04  118558.0  15.694895  18.335793  20.233704  71.178856  21.918627
2021-01-05  119223.0  16.308361  18.269806  20.527573  72.377365  22.448915
2021-01-06  119851.0  16.340931  20.070387  20.346066  74.751030  23.526331
2021-01-07  121956.0  16.829533  21.578730  20.596718  79.630661  24.864679
2021-01-08  125077.0  16.894678  21.295916  21.089380  79.381630  24.494318

In [ ]:
# Calculando o RSL de 10 periodos

p = 10

df_mapa["MM_indice"] = df_mapa["^BVSP"].rolling(p).mean()
df_mapa["MM_ativo1"] = df_mapa["PETR4.SA"].rolling(p).mean()
df_mapa["MM_ativo2"] = df_mapa["FESA4.SA"].rolling(p).mean()
df_mapa["MM_ativo3"] = df_mapa["JBSS3.SA"].rolling(p).mean()
df_mapa["MM_ativo4"] = df_mapa["VALE3.SA"].rolling(p).mean()
df_mapa["MM_ativo5"] = df_mapa["GGBR4.SA"].rolling(p).mean()

In [ ]:
df_mapa["RSL_indice"] = (df_mapa["^BVSP"]/df_mapa["MM_indice"] - 1)*100
df_mapa["RSL_ativo1"] = (df_mapa["PETR4.SA"]/df_mapa["MM_ativo1"] - 1)*100
df_mapa["RSL_ativo2"] = (df_mapa["FESA4.SA"]/df_mapa["MM_ativo2"] - 1)*100
df_mapa["RSL_ativo3"] = (df_mapa["JBSS3.SA"]/df_mapa["MM_ativo3"] - 1)*100
df_mapa["RSL_ativo4"] = (df_mapa["VALE3.SA"]/df_mapa["MM_ativo4"] - 1)*100
df_mapa["RSL_ativo5"] = (df_mapa["GGBR4.SA"]/df_mapa["MM_ativo5"] - 1)*100

In [ ]:
# Calculando o RSI (IFR) de 2 e 14 periodos


indice_rsi2 = ta.momentum.RSIIndicator(close = df_mapa["^BVSP"], window = 2)
indice_rsi14 = ta.momentum.RSIIndicator(close = df_mapa["^BVSP"], window = 14)
ativo1_rsi2 = ta.momentum.RSIIndicator(close = df_mapa["PETR4.SA"], window = 2)
ativo1_rsi14 = ta.momentum.RSIIndicator(close = df_mapa["PETR4.SA"], window = 14)
ativo2_rsi2 = ta.momentum.RSIIndicator(close = df_mapa["FESA4.SA"], window = 2)
ativo2_rsi14 = ta.momentum.RSIIndicator(close = df_mapa["FESA4.SA"], window = 14)
ativo3_rsi2 = ta.momentum.RSIIndicator(close = df_mapa["JBSS3.SA"], window = 2)
ativo3_rsi14 = ta.momentum.RSIIndicator(close = df_mapa["JBSS3.SA"], window = 14)
ativo4_rsi2 = ta.momentum.RSIIndicator(close = df_mapa["VALE3.SA"], window = 2)
ativo4_rsi14 = ta.momentum.RSIIndicator(close = df_mapa["VALE3.SA"], window = 14)
ativo5_rsi2 = ta.momentum.RSIIndicator(close = df_mapa["GGBR4.SA"], window = 2)
ativo5_rsi14 = ta.momentum.RSIIndicator(close = df_mapa["GGBR4.SA"], window = 14)



df_mapa["RSI2_BVSP"] = indice_rsi2.rsi()
df_mapa["RSI14_BVSP"] = indice_rsi14.rsi()

df_mapa["RSI2_PETR"] = ativo1_rsi2.rsi()
df_mapa["RSI14_PETR"] = ativo1_rsi14.rsi()

#arrumar a partir daqui

df_mapa["RSI2_FESA"] = itub_rsi2.rsi()
df_mapa["RSI14_FESA"] = itub_rsi14.rsi()

df_mapa["RSI2_VALE"] = vale_rsi2.rsi()
df_mapa["RSI14_VALE"] = vale_rsi14.rsi()

df_mapa["RSI2_JBSS"] = bbdc_rsi2.rsi()
df_mapa["RSI14_JBSS"] = bbdc_rsi14.rsi()

df_mapa["RSI2_GGBR"] = bbas_rsi2.rsi()
df_mapa["RSI14_GGBR"] = bbas_rsi14.rsi()

NameError: ignored

In [ ]:
df_mapa.head()

In [ ]:
df_mapa["RSL_BVSP"].tail(1)[0]

CRIANDO MAPA

In [ ]:
# Preparando o dataframe

# Agrupando os dados
indicadores = [
                  
                  ["BVSP", df_mapa["RSL_BVSP"].tail(1)[0], df_mapa["RSI14_BVSP"].tail(1)[0]]
                , ["PETR4", df_mapa["RSL_PETR"].tail(1)[0], df_mapa["RSI14_PETR"].tail(1)[0]]
                , ["ITUB4", df_mapa["RSL_ITUB"].tail(1)[0], df_mapa["RSI14_ITUB"].tail(1)[0]]
                , ["VALE3", df_mapa["RSL_VALE"].tail(1)[0], df_mapa["RSI14_VALE"].tail(1)[0]]
                , ["BBDC4", df_mapa["RSL_BBDC"].tail(1)[0], df_mapa["RSI14_BBDC"].tail(1)[0]]
                , ["BBAS3", df_mapa["RSL_BBAS"].tail(1)[0], df_mapa["RSI14_BBAS"].tail(1)[0]]
                , ["OIBR3", df_mapa["RSL_OIBR"].tail(1)[0], df_mapa["RSI14_OIBR"].tail(1)[0]]
                , ["ALUP11", df_mapa["RSL_ALUP"].tail(1)[0], df_mapa["RSI14_ALUP"].tail(1)[0]]
                , ["IRBR3", df_mapa["RSL_IRBR"].tail(1)[0], df_mapa["RSI14_IRBR"].tail(1)[0]]
                , ["TRPL4", df_mapa["RSL_TRPL"].tail(1)[0], df_mapa["RSI14_TRPL"].tail(1)[0]]
                , ["BMGB4", df_mapa["RSL_BMGB"].tail(1)[0], df_mapa["RSI14_BMGB"].tail(1)[0]]
                , ["ENAT3", df_mapa["RSL_ENAT"].tail(1)[0], df_mapa["RSI14_ENAT"].tail(1)[0]]
                , ["AURE3", df_mapa["RSL_AURE"].tail(1)[0], df_mapa["RSI14_AURE"].tail(1)[0]]
                , ["PSSA3", df_mapa["RSL_PSSA"].tail(1)[0], df_mapa["RSI14_PSSA"].tail(1)[0]]
                , ["LUPA3", df_mapa["RSL_LUPA"].tail(1)[0], df_mapa["RSI14_LUPA"].tail(1)[0]]
             ]
 
# Criar o DataFrame do pandas
mapa = pd.DataFrame(indicadores, columns = ["Ativo", "RSL", "RSI14"])

mapa.head(15)

In [ ]:
# Algumas considerações interessantes

plt.plot(df_mapa["RSL_PETR"], df_mapa["RSI2_PETR"], ".", color = "blue")
plt.title("PETR4 - RSL(10) e RSI(2)");

In [ ]:
plt.plot(df_mapa["RSL_PETR"], df_mapa["RSI14_PETR"], ".", color = "blue")
plt.title("PETR4 - RSL(10) e RSI(14)");

In [ ]:
plt.plot(df_mapa["RSL_BVSP"], df_mapa["RSI2_BVSP"], ".", color = "green")
plt.title("ibovespa - RSL(10) e RSI(2)");

In [ ]:
plt.plot(df_mapa["RSL_BBAS"], df_mapa["RSI14_BBAS"], "x", color = "green")
plt.title("BBAS3 - RSL(10) e RSI(14)");

In [ ]:
mapa

In [ ]:
plt.figure(figsize = (18, 10))

plt.scatter(mapa["RSL"], mapa["RSI14"], s = 80)
for i in range(mapa.shape[0]):
    plt.text(x = mapa.RSL[i] + 0.6, y = mapa.RSI14[i] + 0.6 , s = mapa.Ativo[i], 
             fontdict = dict(color = "white", size = 14),
             bbox = dict(facecolor = "black", alpha = 0.7))

plt.xlim(mapa.RSL.min() - 1, mapa.RSL.max() + 5)               
plt.ylim(mapa.RSI14.min() - 2, mapa.RSI14.max() + 4)          

setup = dict(size = 13, color = "black")
plt.text(-10, 52.5, "Mostre-me o dinheiro", **setup)

plt.title("Mapa do RSI e RSL - 2022-10-27") 
plt.xlabel("RSL(10) em %")                        
plt.ylabel("RSI(14)")                     
plt.show()